import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import MainPageDateGameSection from "./MainPageDateGameSection";

const meta = {
  title: "Per Season Components/Game Card Date Wrapper",
  component: MainPageDateGameSection,
  tags: ["autodocs"],
  args: {
    gamesData: {
      "2026-05-15": [
        {
          awayPoints: 139,
          awayTeam: "San Antonio",
          awayTricode: "SAS",
          awaySeed: null,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-15",
          gameId: "0042500236",
          homePoints: 109,
          homeTeam: "Minnesota",
          homeTricode: "MIN",
          homeSeed: null,
          homeWins: null,
          homeLosses: null,
          gameLabel: null,
          gameSubLabel: null,
        },
        {
          awayPoints: 115,
          awayTeam: "Detroit",
          awayTricode: "DET",
          awaySeed: null,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-15",
          gameId: "0042500206",
          homePoints: 94,
          homeTeam: "Cleveland",
          homeTricode: "CLE",
          homeSeed: null,
          homeWins: null,
          homeLosses: null,
          gameLabel: null,
          gameSubLabel: null,
        },
      ],
      "2026-05-13": [
        {
          awayPoints: 117,
          awayTeam: "Cleveland",
          awayTricode: "CLE",
          awaySeed: null,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-13",
          gameId: "0042500205",
          homePoints: 113,
          homeTeam: "Detroit",
          homeTricode: "DET",
          homeSeed: null,
          homeWins: null,
          homeLosses: null,
          gameLabel: null,
          gameSubLabel: null,
        },
      ],
      "2026-05-12": [
        {
          awayPoints: 97,
          awayTeam: "Minnesota",
          awayTricode: "MIN",
          awaySeed: null,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-12",
          gameId: "0042500235",
          homePoints: 126,
          homeTeam: "San Antonio",
          homeTricode: "SAS",
          homeSeed: null,
          homeWins: null,
          homeLosses: null,
          gameLabel: null,
          gameSubLabel: null,
        },
      ],
    },
  },
} satisfies Meta<typeof MainPageDateGameSection>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const WithGameLabels: Story = {
  args: {
    gamesData: {
      "2026-05-05": [
        {
          awayPoints: 90,
          awayTeam: "LA Lakers",
          awayTricode: "LAL",
          awaySeed: 3,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-05",
          gameId: "0042500221",
          homePoints: 108,
          homeTeam: "Oklahoma City",
          homeTricode: "OKC",
          homeSeed: 1,
          homeWins: null,
          homeLosses: null,
          gameLabel: "West Conf. Semifinals",
          gameSubLabel: "Game 1",
        },
        {
          awayPoints: 101,
          awayTeam: "Cleveland",
          awayTricode: "CLE",
          awaySeed: 2,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-05",
          gameId: "0042500201",
          homePoints: 111,
          homeTeam: "Detroit",
          homeTricode: "DET",
          homeSeed: 1,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East Conf. Semifinals",
          gameSubLabel: "Game 1",
        },
      ],
      "2026-05-04": [
        {
          awayPoints: 104,
          awayTeam: "Minnesota",
          awayTricode: "MIN",
          awaySeed: 4,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-04",
          gameId: "0042500231",
          homePoints: 102,
          homeTeam: "San Antonio",
          homeTricode: "SAS",
          homeSeed: 2,
          homeWins: null,
          homeLosses: null,
          gameLabel: "West Conf. Semifinals",
          gameSubLabel: "Game 1",
        },
        {
          awayPoints: 98,
          awayTeam: "Philadelphia",
          awayTricode: "PHI",
          awaySeed: 3,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-04",
          gameId: "0042500211",
          homePoints: 137,
          homeTeam: "New York",
          homeTricode: "NYK",
          homeSeed: 2,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East Conf. Semifinals",
          gameSubLabel: "Game 1",
        },
      ],
      "2026-05-01": [
        {
          awayPoints: 98,
          awayTeam: "LA Lakers",
          awayTricode: "LAL",
          awaySeed: 3,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-01",
          gameId: "0042500176",
          homePoints: 78,
          homeTeam: "Houston",
          homeTricode: "HOU",
          homeSeed: 6,
          homeWins: null,
          homeLosses: null,
          gameLabel: "West First Round",
          gameSubLabel: "Game 6",
        },
        {
          awayPoints: 110,
          awayTeam: "Cleveland",
          awayTricode: "CLE",
          awaySeed: 2,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-01",
          gameId: "0042500136",
          homePoints: 112,
          homeTeam: "Toronto",
          homeTricode: "TOR",
          homeSeed: 7,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 6",
        },
        {
          awayPoints: 93,
          awayTeam: "Detroit",
          awayTricode: "DET",
          awaySeed: 1,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-05-01",
          gameId: "0042500106",
          homePoints: 79,
          homeTeam: "Orlando",
          homeTricode: "ORL",
          homeSeed: 8,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 6",
        },
      ],
      "2026-04-30": [
        {
          awayPoints: 98,
          awayTeam: "Denver",
          awayTricode: "DEN",
          awaySeed: 4,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-30",
          gameId: "0042500166",
          homePoints: 110,
          homeTeam: "Minnesota",
          homeTricode: "MIN",
          homeSeed: 5,
          homeWins: null,
          homeLosses: null,
          gameLabel: "West First Round",
          gameSubLabel: "Game 6",
        },
        {
          awayPoints: 140,
          awayTeam: "New York",
          awayTricode: "NYK",
          awaySeed: 2,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-30",
          gameId: "0042500126",
          homePoints: 89,
          homeTeam: "Atlanta",
          homeTricode: "ATL",
          homeSeed: 7,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 6",
        },
        {
          awayPoints: 93,
          awayTeam: "Boston",
          awayTricode: "BOS",
          awaySeed: 3,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-30",
          gameId: "0042500116",
          homePoints: 106,
          homeTeam: "Philadelphia",
          homeTricode: "PHI",
          homeSeed: 6,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 6",
        },
      ],
      "2026-04-29": [
        {
          awayPoints: 99,
          awayTeam: "Houston",
          awayTricode: "HOU",
          awaySeed: 6,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-29",
          gameId: "0042500175",
          homePoints: 93,
          homeTeam: "LA Lakers",
          homeTricode: "LAL",
          homeSeed: 3,
          homeWins: null,
          homeLosses: null,
          gameLabel: "West First Round",
          gameSubLabel: "Game 5",
        },
        {
          awayPoints: 120,
          awayTeam: "Toronto",
          awayTricode: "TOR",
          awaySeed: 7,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-29",
          gameId: "0042500135",
          homePoints: 125,
          homeTeam: "Cleveland",
          homeTricode: "CLE",
          homeSeed: 2,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 5",
        },
        {
          awayPoints: 109,
          awayTeam: "Orlando",
          awayTricode: "ORL",
          awaySeed: 8,
          awayWins: null,
          awayLosses: null,
          gameDate: "2026-04-29",
          gameId: "0042500105",
          homePoints: 116,
          homeTeam: "Detroit",
          homeTricode: "DET",
          homeSeed: 1,
          homeWins: null,
          homeLosses: null,
          gameLabel: "East First Round",
          gameSubLabel: "Game 5",
        },
      ],
    },
  },
};
